(function(g){var window=this;'use strict';var RA=function(t,p){if(!Number.isFinite(t))return String(t);t=String(t);var Q=t.indexOf(".");Q===-1&&(Q=t.length);var e=t[0]==="-"?"-":"";e&&(t=t.substring(1));p="0".repeat(Math.max(0,p-Q));return e+p+t},uG=function(t){typeof t==="number"?(this.date=j5D(t,0,1),N_(this,1)):g.If(t)?(this.date=j5D(t.getFullYear(),t.getMonth(),t.getDate()),N_(this,t.getDate())):(this.date=new Date(g.af()),t=this.date.getDate(),this.date.setHours(0),this.date.setMinutes(0),this.date.setSeconds(0),this.date.setMilliseconds(0),
N_(this,t))},j5D=function(t,p,Q){p=new Date(t,p,Q);
t>=0&&t<100&&p.setFullYear(p.getFullYear()-1900);return p},N_=function(t,p){t.getDate()!=p&&t.date.setUTCHours(t.date.getUTCHours()+(t.getDate()<p?1:-1))},oA=function(t){if(t.toggleButtonRenderer){var p=t.toggleButtonRenderer;
if(p.isToggled){var Q=p.toggledText?g.c_(p.toggledText):"";t.update({text:Q,icon:vWS(p.toggledIcon)})}else Q=p.defaultText?g.c_(p.defaultText):"",t.update({text:Q,icon:vWS(p.defaultIcon)});t.show()}else t.hide()},byD=function(t,p){!t.toggleButtonRenderer&&p&&p.toggleButtonRenderer?t.toggleButtonRenderer=p.toggleButtonRenderer:p&&p.toggleButtonRenderer||(t.toggleButtonRenderer=null);
oA(t)},vWS=function(t){if(!t)return null;
switch(t.iconType){case "NOTIFICATIONS":return{B:"svg",Lx:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},wm:[{B:"path",Lx:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.64-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.63 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2z"}}]};case "NOTIFICATIONS_NONE":return{B:"svg",Lx:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},wm:[{B:"path",Lx:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z"}}]};
case "NOTIFICATIONS_ACTIVE":return{B:"svg",Lx:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},wm:[{B:"path",Lx:{d:"M7.58 4.08L6.15 2.65C3.75 4.48 2.17 7.3 2.03 10.5h2c.15-2.65 1.51-4.97 3.55-6.42zm12.39 6.42h2c-.15-3.2-1.73-6.02-4.12-7.85l-1.42 1.43c2.02 1.45 3.39 3.77 3.54 6.42zM18 11c0-3.07-1.64-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.63 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2v-5zm-6 11c.14 0 .27-.01.4-.04.65-.14 1.18-.58 1.44-1.18.1-.24.15-.5.15-.78h-4c.01 1.1.9 2 2.01 2z"}}]};
default:return null}},GJD=function(t,p){var Q=g.Y(p,gWA),e=g.Y(p,VtD);
if(p&&(Q||e)){if(Q){var J=Q;var S="notification/add_upcoming_event_reminder"}else e&&(J=e,S="notification/remove_upcoming_event_reminder");S&&J&&J.params&&d1C(t,S,J.params)}},d1C=function(t,p,Q){var e=t.D.V();
t.X||(t.X=new g.xb(e.By));var J={context:g.gi(t.X.config_||g.XE())};g.H_()&&(J.context.clientScreenNonce=g.H_());J.params=Q;Q={timeout:5E3,onError:()=>{r_h(t)},
onTimeout:()=>{r_h(t)}};
e.Jr().X.Kx(g.SJD)&&(Q.onSuccess=S=>{if(S=S.actions)for(let k of S)g.$K(t.D,"innertubeCommand",k)});
g.$L(t.X,p,J,Q)},r_h=function(t){t.toggleButtonRenderer&&(t.toggleButtonRenderer.isToggled=!t.toggleButtonRenderer.isToggled,oA(t))},zz=function(t,p,Q){if(p){var e=p.subtitleText!=null?g.c_(p.subtitleText):"";
Q=Q?Q:p.mainText!=null?g.c_(p.mainText):"";t.update({mainText:Q,subtitleText:e,label:p.mainText?.accessibility?.accessibilityData?.label??Q});g.xs(t.element,"ytp-offline-slate-single-text-line",!e);g.xs(t.L,"ytp-offline-slate-bar-hidden",!Q&&!e)}},T0h=function(t){try{let p=JSON.parse(t);
return p!=null?p:void 0}catch(p){}},C$H=async function(t){var p=t.player.V(),Q=t.getVideoData();
yV(t)&&(Zy3(t)?MtS(t,p,Q):(IgS(t),await x1h(t,p,Q)))},IgS=function(t){var p=t.getVideoData();
if(p.R2)if(p.C("use_rta_for_player"))t.attestationResponse=qRc(t);else{let S=new g.nMH(p);if(g.qa.isInitialized()||t.sequenceNumber>=3){p=Promise;var Q=p.resolve;let k=null;if(S.videoData.rp){var e=g.aT(S);if(e){k={};let w={};e=e.split("&");for(J of e)e=J.split("="),e.length===2&&(w[e[0]]=e[1]);var J=w;J.r1a&&(k.webResponse=J.r1a);J.r1c&&(k.error=OyD[Number(J.r1c)]);k.challenge=S.videoData.rp}}t.attestationResponse=Q.call(p,k||void 0)}}},s5h=function(t){var p=t.getVideoData(),Q=t.player.V();
if(p.isLivePlayback)if(g.z_(Q.S)){t.K=!0;t.J=!0;if(!g.Sl(Q)||g.zw(Q))t.offlineSlate=new YRH(t.player),g.q(t,t.offlineSlate),g.xK(t.player,t.offlineSlate.element,4);(Q=p.getPlayerResponse())&&Q.playabilityStatus&&(t.X=Q.playabilityStatus);t.X?.status!=="UNPLAYABLE"&&(t.X?(p=agC(void 0,t.X.liveStreamability&&t.X.liveStreamability.liveStreamabilityRenderer))?m2(t,p):m2(t,7500):p.C("html5_use_server_init_heartbeat_delay")?(p=$F(t),isNaN(p)||m2(t,p)):m2(t,1E3))}else t.player.KV("html5.unsupportedlive",
2,"HTML5_NO_AVAILABLE_FORMATS_FALLBACK","nolive.1");else g.Uo(p.kZ,"heartbeat")&&t.player.Hy("heartbeat",t.getPlayerType())},P$f=function(t,p,Q){var e=Q.liveStreamability&&Q.liveStreamability.liveStreamabilityRenderer,J=!(!e||!(e.switchStreamsImmediately||e.transitionTiming&&e.transitionTiming==="STREAM_TRANSITION_TIMING_IMMEDIATELY"));
p=agC(p,e);var S=t.getVideoData(),k=t.player.getPlayerStateObject(t.getPlayerType()),w=k.isPlaying()&&!g.Y2(S)&&!t.player.isAtLiveHead(t.getPlayerType());if(S.V().Es()){var f=t.player.gB()?.nH()||{};f.status=Q.status||"";f.dvr=`${+w}`;f["switch"]=`${+J}`;f.ended=`${+!(!e||!e.displayEndscreen)}`;t.player.O("heartbeat",f)}f=e&&e.broadcastId;var u=t.X&&t.X.liveStreamability&&t.X.liveStreamability.liveStreamabilityRenderer&&t.X.liveStreamability.liveStreamabilityRenderer.broadcastId,z=f!==u&&f!=null;
z&&t.player.O("lbidh",{broadcastId:f},!0);if(g.Sl(S.V())&&e&&e.streamTransitionEndpoint){var m=g.Y(e.streamTransitionEndpoint,g.uL)?.commands||[];for(var D of m)if(g.Y(D,g.ir)?.signal==="RELOAD_PLAYER"){t.player.KV("qoe.restart",0,void 0,"sa.reload","7");break}}D=t.player.C("always_cache_redirect_endpoint");if(w&&!J&&!D)return p;m=e&&e.streamTransitionEndpoint&&g.Y(e.streamTransitionEndpoint,g.d5);if((e&&e.transitionTiming)==="STREAM_TRANSITION_TIMING_AT_STREAM_END")t.getVideoData().transitionEndpointAtEndOfStream=
m;else{if(m&&B0h(t,m,Q))return p;D&&!m&&t.getVideoData().transitionEndpointAtEndOfStream&&(t.getVideoData().transitionEndpointAtEndOfStream=void 0)}if(w&&!J&&D)return p;if(Q.status.toUpperCase()==="OK"){if(!g.vV(S)||z)return e={video_id:S.videoId},S.V6&&(e.is_live_destination="1"),e.disable_watch_next=!0,e.raw_watch_next_response=S.getWatchNextResponse(),e.autonav_state=S.autonavState,e.oauth_token=S.oauthToken,e.TG=S.TG,S.vB&&(e.vss_credentials_token=S.vB,e.vss_credentials_token_type=S.BH),S.Z&&
(e.vvt=S.Z),J=void 0,g.vV(S)?z&&(J=new WdM("broadcastIdChanged",`${u},${f}`),Xv("HEARTBEAT_ACTION_TRANSITION_REASON_BROADCAST_ID_CHANGED",Q)):(f&&(J=new WdM("formatsReceived",`${f}`)),Xv("HEARTBEAT_ACTION_TRANSITION_REASON_LIVE_STREAM_WENT_ONLINE",Q)),z&&t.player.O("lbidr",{broadcastId:f}),t.player.loadVideoByPlayerVars(e,void 0,void 0,void 0,J),p;t.player.Hy("heartbeat",t.getPlayerType())}e&&e.displayEndscreen&&(t.offlineSlate?(t=t.offlineSlate,t.Z=!0,t.S&&t.api.cC()):k.isBuffering()&&(S=t.player.gB()?.nH()||
{},t.player.O("hbse",S,!0),t.player.cC(!0,"h"),g.$K(t.player,"onLiveMediaEnded",Q)));return p},Hyh=function(t){var p=t.getVideoData();
!p.C("use_rta_for_player")&&p.R2&&(p=p.botguardData)&&g.Yr(p,t.player.V())},DZ=function(t){t.Z=0;
t.S.stop();t.L=!1;t.sequenceNumber=0},qRc=async function(t){if(await g.X6())return t=t.getVideoData(),g.$M("ENGAGEMENT_TYPE_PLAYBACK",{cpn:t.clientPlaybackNonce,
encryptedVideoId:t.videoId||""},1500);if(t.sequenceNumber>=3)return{error:"ATTESTATION_ERROR_VM_INTERNAL_ERROR"}},$F=function(t){var p=t.getVideoData();
return p.C("html5_use_server_init_heartbeat_delay")?t.heartbeatParams?.interval?t.heartbeatParams.interval*1E3:p.ro:2E3},m2=function(t,p){if(!t.S.isActive()&&t.J){var Q=t.getVideoData();
if(E9(t)||Q.isLivePlayback)p===void 0&&(p=t.L?t.K?7500:t.heartbeatParams?.interval?t.heartbeatParams.interval*1E3:t.getVideoData().ro||6E4:1E3),t.S.start(p)}},Zy3=function(t){var p=t.getVideoData();
if(!g.ZV(t.getVideoData())||p.cG)return!1;if(p.L){t=p.L.flavor==="playready";let Q=p.L.flavor==="widevine"&&p.C("html5_innertube_heartbeats_for_widevine");p=g.p$(p.L)&&p.C("html5_innertube_heartbeats_for_fairplay");return!(t||Q||p)}return!0},E9=function(t){if(Zy3(t))return!!t.heartbeatParams;
var p=t.getVideoData();return!g.ZV(t.getVideoData())||p.Hv||p.n$?!!p.heartbeatToken:!1},hXH=function(t,p,Q){p.BO&&(Q=g.WM(Q,{internalipoverride:p.BO}));
var e={cpn:p.clientPlaybackNonce};p.contextParams&&(e.context_params=p.contextParams);p.Y7&&(e.kpt=p.Y7);Q=g.WM(Q,e);g.Jk(Q,{format:"RAW",method:"GET",timeout:3E4,onSuccess:J=>{if(!t.S.isActive()&&yV(t)){t.W.reset();t.sequenceNumber++;J=J.responseText;var S=T0h(J);if(S){g.$K(t.player,"onHeartbeat",S);var k=S.status==="ok"?S.stop_heartbeat?2:0:S.status==="stop"?1:S.status==="live_stream_offline"?0:-1}else k=(k=J.match(KdC))?k[1]==="0"?0:1:-1;lg7(t,void 0,S,J,k)}},
onError:J=>{yV(t)&&Ln(t,!0,`net-${J.status}`)},
onTimeout:()=>{yV(t)&&Ln(t,!0,"timeout")},
withCredentials:!0})},yV=function(t){var p=t.getVideoData();
return t.player.getPresentingPlayerType()===3||!t.player.V().experiments.Jr().X.Kx(g.iLb)&&t.player.getPlayerStateObject(t.getPlayerType()).X(4)?!1:E9(t)||p.isLivePlayback?!0:(DZ(t),!1)},MtS=function(t,p,Q){if(t.heartbeatParams?.url){var e=g.WM(t.heartbeatParams.url,{request_id:g.Bm()});
Q.Z&&(e=g.WM(e,{vvt:Q.Z}),Q.mdxEnvironment&&(e=g.WM(e,{mdx_environment:Q.mdxEnvironment})));g.jl(p,Q.oauthToken).then(J=>{J&&(e=g.WM(e,{access_token:J}));hXH(t,Q,e)})}},x1h=async function(t,p,Q){var e={videoId:Q.videoId,
sequenceNumber:t.sequenceNumber,heartbeatServerData:Q.C("html5_use_reloaded_heartbeat_server_data")?Q.heartbeatServerData:t.IL??Q.heartbeatServerData};t.N=t.attestationResponse;Q.R2&&(e.attestationResponse=await t.N);var J=g.SR(Q),S=J.client??{};S.utcOffsetMinutes=t.utcOffsetMinutes;e.context=J;e.cpn=Q.clientPlaybackNonce;if(J=typeof Intl!=="undefined"?(new Intl.DateTimeFormat).resolvedOptions().timeZone:null)S.timeZone=J;S={heartbeatChecks:[]};if(J=Q.getPlayerResponse())Q.heartbeatToken&&(e.heartbeatToken=
Q.heartbeatToken),(J=J.playabilityStatus)&&(J=J.liveStreamability)&&J.liveStreamabilityRenderer&&S.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_LIVE_STREAM_STATUS");Q.heartbeatToken&&S.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_YPC");if(g.zw(p)){S.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_UNPLUGGED");var k=FdD(t);J={};k!==null&&(J.clientPlayerPositionUtcMillis=k);k=t.player.pH()?.f7()?.GO()||0;k>0&&(J.freePreviewWatchedDuration={seconds:`${k}`});S.unpluggedParams=J}e.heartbeatRequestParams=S;Q.isLivePlayback?
(S=FdD(t),S!==null&&(e.playbackState||(e.playbackState={}),e.playbackState.playbackPosition={utcTimeMillis:S})):p.C("enable_heartbeat_vod_playback_position")&&(S=A_c(t),S!==null&&(e.playbackState||(e.playbackState={}),e.playbackState.playbackPosition={streamTimeMillis:S}));t.player.qQ("heartbeatRequest",e);var w={timeout:3E4,onSuccess:f=>{if(!t.S.isActive()&&yV(t)){var u=t.getVideoData(),z=u.R2&&t.N==null;u.R2=!!f.heartbeatAttestationConfig?.requiresAttestation||z;z=f.playabilityStatus;var m=JSON.stringify(z)||
"{}";f.authenticationMismatch&&t.player.O("authshear",{});var D=-1;var E=f.playabilityStatus;E&&(g.$K(t.player,"onHeartbeat",E),E.status==="OK"?D=f.stopHeartbeat?2:0:E.status==="UNPLAYABLE"?D=1:E.status==="LIVE_STREAM_OFFLINE"&&(D=0));t.sequenceNumber&&D===-1||t.W.reset();t.sequenceNumber++;!u.C("html5_use_reloaded_heartbeat_server_data")&&f.heartbeatServerData&&(t.IL=f.heartbeatServerData);u.p$=f;(E=f.playerCueRangeSet)&&g.Zp(u,E);f.playerCueRanges&&f.playerCueRanges.length>0&&(u.cueRanges=f.playerCueRanges);
f.progressBarConfig?.progressBarStartPosition&&f.progressBarConfig?.progressBarEndPosition&&(u.progressBarStartPosition=f.progressBarConfig.progressBarStartPosition,u.progressBarEndPosition=f.progressBarConfig.progressBarEndPosition);u.compositeLiveIngestionOffsetToken=f.compositeLiveIngestionOffsetToken;f.compositeLiveStatusToken!==u.compositeLiveStatusToken&&(u.compositeLiveStatusToken=f.compositeLiveStatusToken);u.heartbeatLoggingToken=f.heartbeatLoggingToken;u.C("html5_use_reloaded_heartbeat_server_data")&&
f.heartbeatServerData&&(u.heartbeatServerData=f.heartbeatServerData);u.qQ("dataupdated");lg7(t,f,z,m,D)}},
onError:f=>{yV(t)&&Ln(t,!0,`net-${f.status}`)},
onTimeout:()=>{yV(t)&&Ln(t,!0,"timeout")}};
g.jl(p,g.hN(Q)).then(f=>{f&&(w.kA=`Bearer ${f}`);g.$L(t.XU,"player/heartbeat",e,w)})},FdD=function(t){return(t=t.player.getProgressState(t.getPlayerType()).ingestionTime)&&isFinite(t)?`${Math.floor(t*1E3)}`:null},A_c=function(t){return(t=t.player.getCurrentTime({playerType:t.getPlayerType()}))&&isFinite(t)?`${Math.floor(t*1E3)}`:null},lg7=function(t,p,Q,e,J){J===-1?(Q=`decode ${g.WL(e,3)}`,Ln(t,!1,Q)):J===2?(DZ(t),t.L=!0):(t.Z=0,t.S.stop(),J===1?(t.L=!1,Q&&Q.errorCode==="PLAYABILITY_ERROR_CODE_EMBARGOED"&&
t.player.a7(!0),J=`pe.${Q?.errorCode};ps.${Q?.status}`,t.player.KV("heartbeat.stop",2,t.ux(e),J,void 0,Q?.errorScreen?.playerErrorMessageRenderer),g.CO("heartbeatActionPlayerHalted",U1D(Q)),p?.videoTransitionEndpoint&&Q&&(p=p.videoTransitionEndpoint,(e=g.Y(p,g.d5))&&B0h(t,e,Q,{itct:p?.clickTrackingParams}))):(t.L=!0,e=0,t.K&&Q&&(e=P$f(t,p,Q),t.player.qQ("livestatedata",Q)),e?m2(t,e):m2(t)))},Ln=function(t,p,Q){if(!t.S.isActive()){t.S.stop();
t.Z++;var e=p?"heartbeat.net":"heartbeat.servererror";{let S=t.getVideoData();if(S.BG||p&&!g.ZV(t.getVideoData())&&!E9(t)&&S.isLivePlayback)var J=!1;else t.heartbeatParams?.retries?J=t.heartbeatParams.retries:J=S.yZ||5,J=t.Z>=J}J?(g.CO("heartbeatActionPlayerHalted",p?{enforcedPolicyToHaltOnNetworkFailure:!0}:U1D()),(p=t.getVideoData())&&p.isLivePlayback?t.player.KV(e,1,"Video playback interrupted. Please try again.",Q):t.player.KV(e,1,"Sorry, there was an error while licensing this video.",Q)):(m2(t,
t.W.getValue()),g.nr(t.W))}},U1D=function(t){var p={enforcedPolicyToHaltOnNetworkFailure:!1};
t&&(p.serializedServerContext=t.additionalLoggingData);return p},agC=function(t,p){return(t=Number(t?.pollDelayMs))?t:(p=Number(p?.pollDelayMs))?p:0},B0h=function(t,p,Q,e){var J=p&&p.videoId;
return J?(t.player.qm(J,{autonav:"1",...(e||{})},void 0,!0,!0,p,g.hN(t.getVideoData())),Xv("HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT",Q),!0):!1},Xv=function(t,p){t={trigger:"HEARTBEAT_ACTION_TRIGGER_IMMEDIATE",
reason:t};p&&(t.serializedServerContext=p.additionalLoggingData);g.CO("heartbeatActionPlayerTransitioned",t)};
g.cK.prototype.cC=g.eh(13,function(t,p){this.app.cC(t,1,p)});
g.rK.prototype.cC=g.eh(12,function(t,p=1,Q){this.Kl({playerType:p}).gr(t,void 0,Q)});
var jD={ERAS:["BC","AD"],ERANAMES:["Before Christ","Anno Domini"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:"January February March April May June July August September October November December".split(" "),STANDALONEMONTHS:"January February March April May June July August September October November December".split(" "),SHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),STANDALONESHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),
WEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),STANDALONEWEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),SHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),STANDALONESHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),NARROWWEEKDAYS:"SMTWTFS".split(""),STANDALONENARROWWEEKDAYS:"SMTWTFS".split(""),SHORTQUARTERS:["Q1","Q2","Q3","Q4"],QUARTERS:["1st quarter","2nd quarter","3rd quarter","4th quarter"],AMPMS:["AM","PM"],DATEFORMATS:["EEEE, MMMM d, y",
"MMMM d, y","MMM d, y","M/d/yy"],TIMEFORMATS:["h:mm:ss\u202fa zzzz","h:mm:ss\u202fa z","h:mm:ss\u202fa","h:mm\u202fa"],DATETIMEFORMATS:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5};
jD={ERAS:["BC","AD"],ERANAMES:["Before Christ","Anno Domini"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:"January February March April May June July August September October November December".split(" "),STANDALONEMONTHS:"January February March April May June July August September October November December".split(" "),SHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sept Oct Nov Dec".split(" "),STANDALONESHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sept Oct Nov Dec".split(" "),
WEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),STANDALONEWEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),SHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),STANDALONESHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),NARROWWEEKDAYS:"SMTWTFS".split(""),STANDALONENARROWWEEKDAYS:"SMTWTFS".split(""),SHORTQUARTERS:["Q1","Q2","Q3","Q4"],QUARTERS:["1st quarter","2nd quarter","3rd quarter","4th quarter"],AMPMS:["am","pm"],DATEFORMATS:["EEEE, d MMMM y",
"d MMMM y","d MMM y","dd/MM/y"],TIMEFORMATS:["HH:mm:ss zzzz","HH:mm:ss z","HH:mm:ss","HH:mm"],DATETIMEFORMATS:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],FIRSTDAYOFWEEK:0,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:3};
var OyD=["ATTESTATION_ERROR_UNKNOWN","ATTESTATION_ERROR_VM_NOT_INITIALIZED","ATTESTATION_ERROR_VM_NO_RESPONSE","ATTESTATION_ERROR_VM_TIMEOUT","ATTESTATION_ERROR_VM_INTERNAL_ERROR"],c_D={300:"STREAMING_DEVICES_QUOTA_PER_24H_EXCEEDED",301:"ALREADY_PINNED_ON_A_DEVICE",303:"STOPPED_BY_ANOTHER_PLAYBACK",304:"TOO_MANY_STREAMS_PER_USER",305:"TOO_MANY_STREAMS_PER_ENTITLEMENT",400:"VIDEO_NOT_FOUND",401:"GEO_FAILURE",402:"STREAMING_NOT_ALLOWED",403:"UNSUPPORTED_DEVICE",405:"VIDEO_FORBIDDEN",500:"PURCHASE_NOT_FOUND",
501:"RENTAL_EXPIRED",502:"PURCHASE_REFUNDED",5E3:"BAD_REQUEST",5001:"CGI_PARAMS_MISSING",5002:"CGI_PARAMS_MALFORMED",5100:"AUTHENTICATION_MISSING",5101:"AUTHENTICATION_MALFORMED",5102:"AUTHENTICATION_EXPIRED",5200:"CAST_TOKEN_MALFORMED",5201:"CAST_TOKEN_EXPIRED",5202:"CAST_TOKEN_FAILED",5203:"CAST_SESSION_VIDEO_MISMATCHED",5204:"CAST_SESSION_DEVICE_MISMATCHED",6E3:"INVALID_DRM_MESSAGE",7E3:"SERVER_ERROR",8E3:"RETRYABLE_ERROR"};g.C=uG.prototype;g.C.nE=jD.FIRSTDAYOFWEEK;g.C.pE=jD.FIRSTWEEKCUTOFFDAY;
g.C.clone=function(){var t=new uG(this.date);t.nE=this.nE;t.pE=this.pE;return t};
g.C.getFullYear=function(){return this.date.getFullYear()};
g.C.getYear=function(){return this.getFullYear()};
g.C.getMonth=function(){return this.date.getMonth()};
g.C.getDate=function(){return this.date.getDate()};
g.C.getTime=function(){return this.date.getTime()};
g.C.getDay=function(){return this.date.getDay()};
g.C.getUTCFullYear=function(){return this.date.getUTCFullYear()};
g.C.getUTCMonth=function(){return this.date.getUTCMonth()};
g.C.getUTCDate=function(){return this.date.getUTCDate()};
g.C.getUTCDay=function(){return this.date.getDay()};
g.C.getUTCHours=function(){return this.date.getUTCHours()};
g.C.getUTCMinutes=function(){return this.date.getUTCMinutes()};
g.C.getTimezoneOffset=function(){return this.date.getTimezoneOffset()};
g.C.set=function(t){this.date=new Date(t.getFullYear(),t.getMonth(),t.getDate())};
g.C.setFullYear=function(t){this.date.setFullYear(t)};
g.C.setYear=function(t){this.setFullYear(t)};
g.C.setMonth=function(t){this.date.setMonth(t)};
g.C.setDate=function(t){this.date.setDate(t)};
g.C.setTime=function(t){this.date.setTime(t)};
g.C.setUTCFullYear=function(t){this.date.setUTCFullYear(t)};
g.C.setUTCMonth=function(t){this.date.setUTCMonth(t)};
g.C.setUTCDate=function(t){this.date.setUTCDate(t)};
g.C.add=function(t){if(t.years||t.months){var p=this.getMonth()+t.months+t.years*12,Q=this.getYear()+Math.floor(p/12);p%=12;p<0&&(p+=12);a:{switch(p){case 1:var e=Q%4!=0||Q%100==0&&Q%400!=0?28:29;break a;case 5:case 8:case 10:case 3:e=30;break a}e=31}e=Math.min(e,this.getDate());this.setDate(1);this.setFullYear(Q);this.setMonth(p);this.setDate(e)}t.days&&(Q=this.getYear(),p=Q>=0&&Q<=99?-1900:0,t=new Date((new Date(Q,this.getMonth(),this.getDate(),12)).getTime()+t.days*864E5),this.setDate(1),this.setFullYear(t.getFullYear()+
p),this.setMonth(t.getMonth()),this.setDate(t.getDate()),N_(this,t.getDate()))};
g.C.equals=function(t){return!(!t||this.getYear()!=t.getYear()||this.getMonth()!=t.getMonth()||this.getDate()!=t.getDate())};
g.C.toString=function(){var t=this.getFullYear(),p=t<0?"-":t>=1E4?"+":"";return[p+RA(Math.abs(t),p?6:4),RA(this.getMonth()+1,2),RA(this.getDate(),2)].join("")+""};
g.C.valueOf=function(){return this.date.valueOf()};var gWA=new g.kg("addUpcomingEventReminderEndpoint");var VtD=new g.kg("removeUpcomingEventReminderEndpoint");var tZe=class extends g.fF{constructor(t){super({B:"div",wm:[{B:"button",iW:["ytp-offline-slate-button","ytp-button"],wm:[{B:"div",bV:"ytp-offline-slate-button-icon",zH:"{{icon}}"},{B:"div",bV:"ytp-offline-slate-button-text",zH:"{{text}}"}]}]});this.D=t;this.X=this.toggleButtonRenderer=null;(this.U=this.MQ("ytp-offline-slate-button"))&&this.Hh(this.U,"click",this.L);this.hide()}L(){if(this.toggleButtonRenderer){let t=this.toggleButtonRenderer;t.isToggled?GJD(this,t.toggledServiceEndpoint):GJD(this,
t.defaultServiceEndpoint);t.isToggled=!t.isToggled;oA(this)}}};var YRH=class extends g.fF{constructor(t){super({B:"div",bV:"ytp-offline-slate",wm:[{B:"div",bV:"ytp-offline-slate-background"},{B:"div",bV:"ytp-offline-slate-bar",wm:[{B:"span",bV:"ytp-offline-slate-icon",wm:[{B:"svg",Lx:{fill:"#fff",height:"100%",viewBox:"0 0 24 24",width:"100%"},wm:[{B:"path",Lx:{d:"M16.94 6.91l-1.41 1.45c.9.94 1.46 2.22 1.46 3.64s-.56 2.71-1.46 3.64l1.41 1.45c1.27-1.31 2.05-3.11 2.05-5.09s-.78-3.79-2.05-5.09zM19.77 4l-1.41 1.45C19.98 7.13 21 9.44 21 12.01c0 2.57-1.01 4.88-2.64 6.54l1.4 1.45c2.01-2.04 3.24-4.87 3.24-7.99 0-3.13-1.23-5.96-3.23-8.01zM7.06 6.91c-1.27 1.3-2.05 3.1-2.05 5.09s.78 3.79 2.05 5.09l1.41-1.45c-.9-.94-1.46-2.22-1.46-3.64s.56-2.71 1.46-3.64L7.06 6.91zM5.64 5.45L4.24 4C2.23 6.04 1 8.87 1 11.99c0 3.13 1.23 5.96 3.23 8.01l1.41-1.45C4.02 16.87 3 14.56 3 11.99s1.01-4.88 2.64-6.54z"}},
{B:"circle",Lx:{cx:"12",cy:"12",r:"3"}}]}]},{B:"span",bV:"ytp-offline-slate-messages",wm:[{B:"div",bV:"ytp-offline-slate-main-text",Lx:{"aria-label":"{{label}}"},zH:"{{mainText}}"},{B:"div",bV:"ytp-offline-slate-subtitle-text",zH:"{{subtitleText}}"}]},{B:"span",bV:"ytp-offline-slate-buttons"}]},{B:"button",iW:["ytp-offline-slate-close-button","ytp-button"],wm:[g.lu()]},{B:"button",iW:["ytp-offline-slate-open-button","ytp-button"],wm:[g.KY()]}]});this.api=t;this.X=this.U=null;this.background=this.MQ("ytp-offline-slate-background");
this.L=this.MQ("ytp-offline-slate-bar");this.J=new g.bP(()=>{g.Z2(this.L,"ytp-offline-slate-bar-fade")},15E3);
this.Z=!1;this.W=new g.bP(()=>{g.Z2(this.element,"ytp-offline-slate-collapsed")},15E3);
g.q(this,this.W);g.q(this,this.J);this.countdownTimer=new g.bP(this.N,1E3,this);this.Hh(t,"presentingplayerstatechange",this.A);this.Hh(t,"livestatedata",this.T1);this.Hh(this.MQ("ytp-offline-slate-close-button"),"click",()=>{g.Z2(this.element,"ytp-offline-slate-collapsed")});
this.Hh(this.MQ("ytp-offline-slate-open-button"),"click",()=>{g.IV(this.element,"ytp-offline-slate-collapsed")});
this.hide();t=this.getVideoData();t.getPlayerResponse()&&(t=t.getPlayerResponse().playabilityStatus)&&this.T1(t);t=this.api.getPresentingPlayerType()===8&&!this.getVideoData().mV;var p=this.api.getPresentingPlayerType()===8;g.xs(this.element,"ytp-offline-slate-premiere-trailer",t);g.xs(this.element,"ytp-offline-slate-hide-background",p)}getPlayerType(){if(this.api.getPresentingPlayerType()===8)return 1}getVideoData(){return this.api.getVideoData({playerType:this.getPlayerType()})}T1(t){var p=t?.liveStreamability?.liveStreamabilityRenderer?.offlineSlate;
if(p){this.U=t;p=p.liveStreamOfflineSlateRenderer;p.canShowCountdown?this.N():zz(this,p);var Q=t?.liveStreamability?.liveStreamabilityRenderer?.offlineSlate?.liveStreamOfflineSlateRenderer?.thumbnail;if(Q){let e=0,J=null;Q=Q.thumbnails;for(let S=0;S<Q.length;S++)Q[S].width>e&&(e=Q[S].width||0,J=Q[S].url);J&&(this.background.style.backgroundImage=`url(${J})`)}else this.background.style.backgroundImage="";p.actionButtons?(this.X||(this.X=new tZe(this.api),this.X.lV(this.MQ("ytp-offline-slate-buttons")),
g.q(this,this.X)),byD(this.X,p.actionButtons&&p.actionButtons[0])):this.X&&byD(this.X,null);this.U=t}else this.U=null;this.A()}A(t){if(this.api.getPresentingPlayerType()===8)var p=!0;else{var Q=this.api.getPlayerStateObject(),e=this.getVideoData();p=e.isLivePlayback&&(Q.isBuffering()||Q.X(2)||Q.X(64));var J=e.autonavState===2&&Q.X(2);Q=Q.isPlaying()&&!g.Y2(e)&&!this.api.isAtLiveHead(void 0,!0);p=p&&!Q&&!J}p&&this.U?this.S?t?.sQ(2)&&!this.getVideoData().mV&&(g.IV(this.element,"ytp-offline-slate-collapsed"),
this.W.stop(),g.IV(this.L,"ytp-offline-slate-bar-fade"),this.J.start()):(this.show(),this.W.start(),this.api.qQ("offlineslatestatechange"),this.Z&&this.api.cC()):this.S&&(this.hide(),this.api.qQ("offlineslatestatechange"))}N(){var t=this.U?.liveStreamability?.liveStreamabilityRenderer?.offlineSlate?.liveStreamOfflineSlateRenderer;if(t){var p=Math.floor(g.af()/1E3),Q=t.canShowCountdown&&Number(t.scheduledStartTime);!Q||Q<=p?(zz(this,t),this.countdownTimer.stop()):(p=g.ai(Q-p),zz(this,t,p),g.gj(this.countdownTimer))}}EL(){this.countdownTimer.dispose();
this.countdownTimer=null;super.EL()}};var WdM=class{constructor(t,p){var Q=(0,g.K)();this.module="heartbeat";this.trigger=t;this.X=p;this.U=Q}S(t){return this.trigger&&t.trigger?this.module===t.module&&this.trigger===t.trigger&&this.X===t.X:!1}isExpired(){return(0,g.K)()-this.U>6E4}toString(){return`${this.module}:${this.trigger}:${this.X}`}};var KdC=/^GLS\/1.0 (\d+) (\w+).*?\r\n\r\n([\S\s]*)$/;g.TN("heartbeat",class extends g.L8{constructor(t){super(t);this.J=!1;this.Z=0;this.L=!1;this.S=new g.bP(()=>{C$H(this)},0);
this.X=this.heartbeatParams=null;this.K=!1;this.W=new g.fr(1E3,6E4,1);this.sequenceNumber=0;this.offlineSlate=null;this.XU=new g.xb(void 0);this.attestationResponse=Promise.resolve(void 0);this.N=Promise.resolve(void 0);this.utcOffsetMinutes=-(new uG).getTimezoneOffset();this.U=new g.aM(this);g.q(this,this.S);g.q(this,this.U);IgS(this);s5h(this);this.U.Hh(t,"heartbeatparams",this.U5);this.U.Hh(t,"presentingplayerstatechange",this.nx);this.U.Hh(t,"videoplayerreset",this.A);this.U.Hh(t,g.tX("heartbeat"),
this.onCueRangeEnter);this.K&&this.X&&P$f(this,void 0,this.X);var p=new g.pm(1E3,0x7ffffffffffff,{priority:1,namespace:"heartbeat"}),Q=new g.pm(0x8000000000000,0x8000000000000,{id:"stream_end",priority:1,namespace:"heartbeat"});t.E9([p,Q]);Hyh(this)}EL(){DZ(this);this.player.FM("heartbeat");super.EL()}onCueRangeEnter(){var t=this.getVideoData();this.J=!0;t.C("html5_use_server_init_heartbeat_delay")?(t=$F(this),isNaN(t)||m2(this,t)):m2(this,2E3)}U5(t){var p=this.getVideoData();this.heartbeatParams=
t;p.C("html5_use_server_init_heartbeat_delay")?(t=$F(this),isNaN(t)||m2(this,t)):m2(this,2E3)}nx(t){if(this.player.getPresentingPlayerType()!==8&&this.X?.status!=="UNPLAYABLE")if(t.state.X(2)||t.state.X(64))DZ(this),this.K&&(this.J=!0,this.getVideoData().C("html5_use_server_init_heartbeat_delay")?(t=$F(this),isNaN(t)||m2(this,t)):m2(this,1E3));else{let p=this.player.V().experiments.Jr().X.Kx(g.iLb);(t.state.X(1)||t.state.X(8)||p&&t.state.X(4))&&m2(this,$F(this))}}A(){this.player.getPresentingPlayerType()!==
3&&m2(this,$F(this))}getPlayerType(){if(this.player.getPresentingPlayerType()===8)return 1}getVideoData(){return this.player.getVideoData({playerType:this.getPlayerType()})}YE(t){switch(t){case 4:case 3:return!1}return!0}ux(t){var p="LICENSE",Q=T0h(t);if(Q)return Q.reason||g.Fq[p]||"";if(t=t.match(KdC))if(t=Number(t[1]))p=(p=c_D[t.toString()])?p:"LICENSE";return g.Fq[p]||""}I3(){return!!this.offlineSlate&&this.offlineSlate.S}});})(_yt_player);
